version: "3.7"

services:
  database:
    image: postgres
    container_name: database-integracoes
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=integracoes
      - POSTGRES_DB=integracoes
    volumes:
      - pgdata:/data/postgres
    network_mode: host

  redis:
    container_name: redis-integracoes
    image: redis:alpine
    ports:
      - 6379:6379

  app:
    build: .
    container_name: app-integracoes
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    network_mode: host

volumes:
  pgdata:
    driver: local
